### ISSUE TITLE
Add icons for video resources

### ISSUE THREAD

**Issue by bhavaniak** [iupui-soic/mHBS_tracker#82] opened 2018-03-20 19:12 UTC
Icons should be added as there are only titles displayed which makes it look little ambiguous.

**Comment by Ezmeyers** [comment] 2018-03-20 20:20
@bhavaniak which icons are these referring to

**Comment by Ezmeyers** [comment] 2018-03-20 20:26
duplicate of https://github.com/iupui-soic/mHBS_tracker/issues/75

**Closed by Ezmeyers** 2018-03-20 20:26 UTC
