### ISSUE TITLE
Show the list of downloads when we hit download button in the app

### ISSUE THREAD

**Issue by bhavaniak** [iupui-soic/mHBS_tracker#85] opened 2018-03-20 19:20 UTC
As discussed in the meeting, when the user hits the download button, he/she must also be able to see the list of downloads already made.

**Comment by Ezmeyers** [comment] 2018-03-20 20:18
duplicate of https://github.com/iupui-soic/mHBS_tracker/issues/77

**Closed by Ezmeyers** 2018-03-20 20:18 UTC
